art_styles_collection = [
    "Impressionism",
    "Cubism",
    "Surrealism",
    "Abstract Expressionism",
    "Pop Art",
    "Realism",
    "Renaissance",
    "Baroque",
    "Minimalism",
    "Fauvism",
    "Dadaism",
    "Post-Impressionism",
    "Pointillism",
    "Art Nouveau",
    "Expressionism",
    "Romanticism",
    "Symbolism",
    "Constructivism",
    "Gothic",
    "Op Art",
    "Photorealism",
    "Conceptual Art",
    "Installation Art",
    "Neo-Expressionism",
    "Land Art",
    "Digital Art",
    "Graffiti Art",
    "Street Art",
    "Kinetic Art",
    "New Media Art",
    "Classical Art",
    "Hyperrealism",
    "Surrealist Sculpture",
    "Deco Art",
    "Contemporary Art",
    "Art Brut",
    "Neo-Dada",
    "Abstract Art",
    "Metaphysical Art",
    "Suprematism",
    "Bauhaus",
    "Social Realism",
    "Cinematic Art",
    "Video Art",
    "Trompe-l'oeil",
    "Body Art",
    "Naïve Art",
    "Tachisme",
    "Analytical Cubism",
    "Synthetic Cubism"
]
